api_platform:
    version: '0.1-beta.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    http_cache:
        etag: true
        max_age: 0
        shared_max_age: 3600
        public: true
        invalidation:
            enabled: false
