security:
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: apiKey
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            access_denied_handler: App\Security\AccessDeniedHandler
            entry_point: App\Security\EntryPointService 
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
