security:
  # you must use the authenticator manager for login throttling
  # https://symfony.com/doc/current/security.html#limiting-login-attempts
  enable_authenticator_manager: true
  password_hashers:
    # Use native password hasher, which auto-selects and migrates the best
    # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    user_provider:
      entity:
        class: App\Entity\User
        property: secretKey
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt))/
      security: false
    public:
      pattern: ^/(public|images)/
      security: false
    main:
      lazy: true
      login_throttling:
        max_attempts: 5
        interval: '15 minutes'
      json_login:
        check_path: /login
        username_path: security.credentials.login
        password_path: security.credentials.password
      custom_authenticators:
        - App\Security\ApiKeyAuthenticator
