monolog:
  # https://symfony.com/doc/current/logging/channels_handlers.html#configure-additional-channels-without-tagged-services
  channels: ["zusam"]
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [404, 405]
    nested:
      type: rotating_file
      level: debug
      channels: ["!event", "!php", "!zusam"]
      max_files: 10
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
    deprecation:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
      max_files: 10
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ["php"]
    zusam:
      type: rotating_file
      path: "%kernel.logs_dir%/zusam.log"
      level: error
      channels: ["zusam"]
      max_files: 10
