monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: main
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
