monolog:
  # https://symfony.com/doc/current/logging/channels_handlers.html#configure-additional-channels-without-tagged-services
  channels: ["zusam"]
  handlers:
    main:
      type: stream
      level: debug
      channels: ["!event", "!zusam"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
    zusam:
      type: rotating_file
      path: "%kernel.logs_dir%/zusam.log"
      level: debug
      channels: ["zusam"]
      max_files: 10
