monolog:
    handlers:
        main:
            type: stream
            level: debug
            channels: ["!event", "!zusam"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
