name: PHPUnit Tests

on: [pull_request]

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.0', '8.1', '8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, curl, dom, fileinfo, iconv, intl, json, mbstring, pdo_sqlite, imagick, posix, simplexml, xml, xmlwriter
          coverage: none

      - name: Validate composer.json and composer.lock
        run: cd api && composer validate --strict

      - name: Install dependencies
        run: cd api && composer install --prefer-dist --no-progress

      - name: Run PHPUnit tests
        run: cd api && php bin/phpunit
